language: csharp
solution: Sandbox.sln
install:
    - nuget restore TestSandbox1/TestSandbox1.sln
    - nuget restore TestSandbox2/TestSandbox2.sln
    - nuget restore TestSandbox3/TestSandbox3.sln
    - nuget restore TestSandbox4/TestSandbox4.sln
    - nuget restore TestSandbox5/TestSandbox5.sln
    - nuget restore TestSandbox6/TestSandbox6.sln
    - nuget restore TestSandbox7/TestSandbox7.sln
    - nuget restore TestSandbox8/TestSandbox8.sln
    - nuget restore TestSandbox9/TestSandbox9.sln
    - nuget restore Sandbox.sln
notifications:
  email: false
