language: csharp
solution: Sandbox.sln
install:
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget restore Sandbox.sln
