-
  branches:
    only:
    - master

  before_build:
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget install NUnitGo
    - nuget uninstall NUnitGo
    - nuget restore Sandbox.sln

  build_script: 
    - msbuild Sandbox.sln /p:Configuration=Release /t:Rebuild
        
  test:
    assemblies:
      - '**\*box.dll'
